// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ98JsblR6i2p73kWvkJD7-quLH16bJ2I',
    appId: '1:507798420275:web:b346a464f357d0e1bc1c46',
    messagingSenderId: '507798420275',
    projectId: 'task-firestore-9f039',
    authDomain: 'task-firestore-9f039.firebaseapp.com',
    storageBucket: 'task-firestore-9f039.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9iq_yyK7v7_E08PnajfRX_Vcr094ap7k',
    appId: '1:507798420275:android:363bd32d550d1193bc1c46',
    messagingSenderId: '507798420275',
    projectId: 'task-firestore-9f039',
    storageBucket: 'task-firestore-9f039.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMy9_gPZ2_kJbGeudp4ponhuqJxcnwsKI',
    appId: '1:507798420275:ios:261a10ad2f2a067bbc1c46',
    messagingSenderId: '507798420275',
    projectId: 'task-firestore-9f039',
    storageBucket: 'task-firestore-9f039.appspot.com',
    iosClientId: '507798420275-r2j4l0l4pjukcdkrpav8sb6rin8r25li.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoAppFire',
  );
}
